### ISSUE TITLE
Expected positive integer for height but received 2779.5 of type number

### ISSUE THREAD

**Issue by longd3** [marlokessler/strapi-plugin-image-optimizer#27]
Error: Expected positive integer for height but received 2779.5 of type number
    at Object.invalidParameterError (/home/long/work/sea/sea-cms/node_modules/sharp/lib/is.js:135:10)
    at Sharp.resize (/home/long/work/sea/sea-cms/node_modules/sharp/lib/resize.js:287:18)
    at sharpAddResizeSettings (/home/long/work/sea/sea-cms/node_modules/strapi-plugin-image-optimizer/dist/server/services/image-optimizer-service.js:88:26)
    at resizeFileTo (/home/long/work/sea/sea-cms/node_modules/strapi-plugin-image-optimizer/dist/server/services/image-optimizer-service.js:51:21)
    at generateImage (/home/long/work/sea/sea-cms/node_modules/strapi-plugin-image-optimizer/dist/server/services/image-optimizer-service.js:42:21)
    at /home/long/work/sea/sea-cms/node_modules/strapi-plugin-image-optimizer/dist/server/services/image-optimizer-service.js:29:46
    at Array.forEach (<anonymous>)
    at /home/long/work/sea/sea-cms/node_modules/strapi-plugin-image-optimizer/dist/server/services/image-optimizer-service.js:28:39
    at Array.forEach (<anonymous>)
    at /home/long/work/sea/sea-cms/node_modules/strapi-plugin-image-optimizer/dist/server/services/image-optimizer-service.js:25:15

**Comment by netzpixel** [comment]
Same. Why is this still open?

**Comment by christophebe** [comment]
Same issue

**Comment by rosareyes** [comment]
same?

**Comment by raku3** [comment]
additionalResolutions: [1.5, 3],
↑ remove

It appears that you have resized the image and as a result the file specifies a pixel dimension with a decimal point.
Files containing decimal points will result in an error
