### ISSUE TITLE
Javascript vs Typescript (Strapi project)

### ISSUE THREAD

**Issue by robozb** [marlokessler/strapi-plugin-image-optimizer#47]
I don't know but it seems it doesn't work if the Strapi project is a pure javascript project:

Exception during the image upload:

```
[2024-12-17 01:59:19.097] error: isImage is not a function
TypeError: isImage is not a function
    at Object.enhanceAndValidateFile (D:\Kivitelezes2\ITWebfocusHu\strapi\node_modules\@strapi\plugin-upload\server\services\upload.js:172:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doUpload (D:\Kivitelezes2\ITWebfocusHu\strapi\node_modules\@strapi\plugin-upload\server\services\upload.js:204:26)
    at async Promise.all (index 0)
    at async Object.upload (D:\Kivitelezes2\ITWebfocusHu\strapi\node_modules\@strapi\plugin-upload\server\services\upload.js:208:23)    
    at async uploadFiles (D:\Kivitelezes2\ITWebfocusHu\strapi\node_modules\@strapi\plugin-upload\server\controllers\admin-upload.js:79:27)
    at async Object.upload (D:\Kivitelezes2\ITWebfocusHu\strapi\node_modules\@strapi\plugin-upload\server\controllers\admin-upload.js:101:5)
    at async returnBodyMiddleware (D:\Kivitelezes2\ITWebfocusHu\strapi\node_modules\@strapi\strapi\dist\services\server\compose-endpoint.js:42:18)
    at async policiesMiddleware (D:\Kivitelezes2\ITWebfocusHu\strapi\node_modules\@strapi\strapi\dist\services\server\policy.js:15:5)   
    at async D:\Kivitelezes2\ITWebfocusHu\strapi\node_modules\@strapi\strapi\dist\services\server\compose-endpoint.js:27:12

```

package.json

```
  "dependencies": {
    "@retikolo/drag-drop-content-types": "^1.3.10",
    "@strapi/plugin-cloud": "4.23.0",
    "@strapi/plugin-documentation": "^4.23.0",
    "@strapi/plugin-i18n": "4.23.0",
    "@strapi/plugin-users-permissions": "4.23.0",
    "@strapi/strapi": "4.23.0",
    "better-sqlite3": "8.6.0",
    "mysql": "^2.18.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "strapi-plugin-image-optimizer": "^2.2.1",
    "styled-components": "5.3.3"
  },
```

src/extensions/upload/strapi-server.js

```

const imageOptimizerService = require("strapi-plugin-image-optimizer/dist/server/services/image-optimizer-service.js");

module.exports = (plugin) => {
  plugin.services["image-manipulation"] = imageOptimizerService;
  plugin.contentTypes.file.lifecycles = require('./content-types/file/lifecycles');
  return plugin;
};
```

**Comment by robozb** [comment]
It seems with this little `.default` the problem is solved

```
const imageOptimizerService = require("strapi-plugin-image-optimizer/dist/server/services/image-optimizer-service.js").default;;

console.log("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
console.log("imageOptimizerService:", imageOptimizerService);
console.log("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");

module.exports = (plugin) => {
  plugin.services["image-manipulation"] = imageOptimizerService;
  plugin.contentTypes.file.lifecycles = require('./content-types/file/lifecycles');
  return plugin;
};
```
